export const SocketMsgType = {
  IS_USER: 'IS_USER',
  NEW_USER: 'NEW_USER',
  INIT_CHATS: 'INIT_CHATS',
  LOGOUT: 'LOGOUT',
  DISCONNECT: 'DISCONNECT',
  MESSAGE_SEND: 'MESSAGE_SEND',
  P_MESSAGE_SEND: 'P_MESSAGE_SEND',
  TYPING: 'TYPING',
  P_TYPING: 'P_TYPING',
  CHECK_CHANNEL: 'CHECK_CHANNEL',
  CREATE_CHANNEL: 'CREATE_CHANNEL',
};
